# This is an example ArgoCD App that uses the Helm provider
# to deploy a virtual cluster.

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vcluster
  namespace: argocd
spec:
  project: default
  source:
    chart: vcluster
    repoURL: https://charts.loft.sh
    targetRevision: "0.21.2"
    helm:
      releaseName: vcluster
      valuesObject:
        sync:
          toHost:
            ingresses:
              enabled: true
        controlPlane:
          coredns:
            enabled: true
            embedded: true
  destination:
    server: https://kubernetes.default.svc
    namespace: vcluster
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true